### ISSUE TITLE
Official InversifyJS example

### ISSUE THREAD

**Issue by remojansen** [Talento90/typescript-node#2]
Hi I'm the author of InnversifyJS we have an [official repository for examples](https://github.com/inversify/inversify-code-samples). As you can see [here](https://github.com/inversify/InversifyJS/issues?q=is%3Aissue+is%3Aopen+label%3AExample) I was planning to add a node + express example but your example uses hapi but that would be good too :smile:

Would you like to contribute this example to the official InversifyJS examples?

**Comment by Talento90** [comment]
Yes, it's a pleasure for me to have the possibility to contribute for the community :+1: 
I will send you a PR request tomorrow :)

**Comment by remojansen** [comment]
Thanks a lot :smile:
