### ISSUE TITLE
Inversify update 

### ISSUE THREAD

**Issue by zolekm** [Talento90/typescript-node#4]
Hi as from inversify beta.9 there is no IKernel exported anymore you need to use it like this, can you update seed with thees breaking changes?

`import { Kernel, interfaces } from "inversify";

let kernel: interfaces.Kernel = new Kernel();

kernel.bind<interfaces.Factory<Weapon>>("Weapon").toFactory<Weapon>((context) => {
        return () => {
            return kernel.get<Weapon>("Weapon");
        };
});`

Best, M

**Comment by zolekm** [comment]
To fix all issues i need to update MongoRepository with @injectable() annotation and ioc lib dev and test with interfaces dep

Best M

**Comment by Talento90** [comment]
I will fix it on the weeken! But you can do a PR :+1:

**Comment by Talento90** [comment]
Thanks for your input :+1: 

Now you can clone it without any problems!

**Comment by zolekm** [comment]
@Talento90 thank you :)
