### ISSUE TITLE
3rd party lib interaction and routing

### ISSUE THREAD

**Issue by zolekm** [Talento90/typescript-node#5]
Hey @Talento90,

i think this seed will need an option to interact with 3rd party library so there will need to be some service folder that make this possible. In services can be logic to integrate Facebook, Slack, S3...

Next what i think this seed need separated routing for each controller(todos, users)

Example for routes:
**- controllers**
--users
--todos
**- routes**
--users
--todos

What do you think about this?

Best M

**Comment by Talento90** [comment]
Yeah I agree, I also prefer feature oriented rather than component oriented! 

I think that a good option is to create a authentication folder inside libs with all strategies!

**Comment by Talento90** [comment]
@zolekm I have opened a [issue ](https://github.com/Talento90/typescript-node/issues/6) to refactor the project to Feature Oriented.

**Comment by zolekm** [comment]
@Talento90 thats sounds great i like that approach

**Comment by Talento90** [comment]
@zolekm  Hey man how are you? I changed the project structure and also I added jwt authentication, can you take a look?

**Comment by zolekm** [comment]
@Talento90 Hey this is great i think you have done great job. But i think there is space to do some modifications. For example personally i will move plugins and configuration folder in root of project to be easy access when needed

**Comment by Talento90** [comment]
Thanks man :+1:  I have to disagree about the plugins folder, because they are supposed to be required only once in the server creation. If we have 10 plugins it will spam the root folder.
